### PR TITLE
Replicate API Added

### PR DESCRIPTION
**Pull request by zsxkib**
Hey this model is absolutely amazing, great work!!

We've added it to replicate: https://replicate.com/zsxkib/instant-id
And all the files needed to run in cog can be found in this PR
We'd really appreciate if you could merge this

Thank you so much for your contribution to the AI community

### CODE REVIEW

**Comment by haofanwang** [comment]
Thank you so much❤️

**Comment by haofanwang** [comment]
Why you want to add other files? I think add it in README.md is enoght?

**Comment by zsxkib** [comment]
The other files (`cog.yaml`, `predict.py`) means that any user with a GPU can easily run your model locally, using [Cog](https://github.com/replicate/cog) containers, there's no need what so ever to think about downloading weights, installing cuda versions, etc. Thinks just work.

_E.g. a user can run `cog predict -i image=@examples/sam_resize.png -i width=1024 -i height=1024` after cloning and using [Cog](https://github.com/replicate/cog), everything will just run!_

Let me know what you think @haofanwang :))

**Comment by haofanwang** [comment]
I see. Can you add a few lines to explain how to use in README.md? @zsxkib

**Comment by zsxkib** [comment]
Hey @haofanwang

I've made the changes you asked for:
- `cog/predict.py`
    File runs when user calls `cog predict -i ...`
- `cog/README.md`
    A README explaining what Cog is, how it works, etc.
- `cog.yaml`
    Unfortunately, this file has to be in the root dir for Cog to work properly.
- `.gitignore`
    I've added one line for a hidden `.cog` folder.
- `README.md`
    I've added one line to add a Replicate badge so that people can run it in a web UI.

I hope this helps :))

**Comment by haofanwang** [comment]
LGTM, thank you❤️!

**Pull request merged**
