### PR TITLE
LCM + ControlnetPose Gradio Examples

### PR DESCRIPTION
**Pull request by radames**
This PR brings
* Option to Enable fast inference with LCM 
* ControlnetPose Example
* Script to download the models `download_models.py`
* brought enhance_face_region from Spaces to demo here

### CODE REVIEW

**Comment by chengxiaobo1988** [comment]
unnamed

**Comment by radames** [comment]
hi @nosiu , you're right the region control with control_mask it's not on the github repo, you can find it [here](https://huggingface.co/spaces/InstantX/InstantID/tree/main) , I'm discussion with authors in order to bring it here as well

**Comment by johndpope** [comment]
in this PR - there's a mask used
https://github.com/InstantID/InstantID/pull/89

**Comment by dezigns333** [comment]
How could I adapt this to use objects and logos and put them on things like signs or shirts in the image? A non face-id images would be useful for designers.

**Comment by ResearcherXman** [comment]
I fixed some bugs and adjusted the code structure base on your commits in https://github.com/InstantID/InstantID/pull/114. Thanks and closed.

**Pull request closed without merging**
